/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GenerateChart: typeof import('./components/charts/GenerateChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RadialBarGauge: typeof import('./components/charts/RadialBarGauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsersChart: typeof import('./components/charts/UsersChart.vue')['default']
  }
}
